#!/usr/bin/env bash

echo_jira_ticket_url() {
  echo "https://$BP_JIRA_ORGANIZATION.atlassian.net/browse/$1";
  return 0;
}

jira() {
  local ticket=$1;
  [[ -z $1 ]] && ticket=$(echo_current_branch);
  validate_jira_branch $ticket &&
    run_cmd "open $(echo_jira_ticket_url $ticket)";
}

validate_jira_branch() {
  if [[ -z $BP_JIRA_ORGANIZATION ]]; then
    print_error "BP_JIRA_ORGANIZATION is not defined on the shell configuration file."
    return 1;
  fi

  if [[ -z $(echo_regex_substring $1 "^[[:alpha:]]+-[[:digit:]]+") ]]; then
    print_error "Branch `color_yellow $1` is not a valid ticket name.";
    return 1;
  fi
}
