#!/usr/bin/env bash

__get_ps1_current_path() { echo "%~"; }
[ ${BASH_VERSION} ] && __get_ps1_current_path() { echo "\w"; }

prompt_command() {
  local ps1_path="$(prompt_bg_white " $(__get_ps1_current_path) ")";
  local git_root=$(git rev-parse --show-toplevel 2>/dev/null);
  local branch=" ";
  if [[ -n $git_root ]]; then
    local repository="`basename $git_root`";
    local remaining_path=${PWD#"$git_root"};
    if [[ -z $remaining_path ]]; then 
      ps1_path="$(prompt_bg_blue " $repository ")"; 
    else
      local remaining_path_color=$(prompt_bg_white "$(prompt_fg_black "$remaining_path ")");
      ps1_path="$(prompt_bg_blue " $repository")$remaining_path_color";
    fi

    local current_branch=$(echo_current_branch);
    branch=" `prompt_fg_green $current_branch` ";
    if [ "$(git status 2> /dev/null | tail -n1)" != "nothing to commit, working tree clean" ]; then
      branch=" `prompt_fg_yellow $current_branch` ";
    fi
  fi
  PS1="$(prompt_fg_black "$ps1_path")$branch`prompt_fg_magenta \$` ";
}

[ ${BASH_VERSION} ] && PROMPT_COMMAND=prompt_command;
[ ${ZSH_VERSION} ] && precmd() { prompt_command; }