#!/usr/bin/env bash
SHELLCHEMY_VERSION="v1.0.0";

echo "🧪 `color_green shellchemy` $SHELLCHEMY_VERSION (`color_magenta $SYSTEM_NAME`)";

shellchemy() {
  if [[ -z $1 || $1 == "help" ]]; then
    print_info "$(cat <<EOF
usage: shellchemy [cd] [restart] [update] [version] [vsc]
    $(color_cyan cd)       Change directory to shellchemy
    $(color_cyan help)     Show shellchemy available commands
    $(color_cyan restart)  Apply changes made to files under shellchemy directory
    $(color_cyan update)   Pull new changes and restart shellchemy
    $(color_cyan version)  Shows the current version of shellchemy
    $(color_cyan vsc)      Open shellchemy directory in Visual Studio Code and change directory
EOF
)"
  elif [[ $1 == "cd" ]]; then
    __shellchemy_cd;
  elif [[ $1 == "restart" ]]; then
    __shellchemy_restart;
  elif [[ $1 == "update" ]]; then
  elif [[ $1 == "version" || $1 == "--version" ]]; then
    echo "$SHELLCHEMY_VERSION";
  elif [[ $1 == "vsc" ]]; then
    vsc "$shellchemy_path";
    __shellchemy_cd;
  else
    print_error "`color_red $1` is not a shellchemy command. See `color_cyan "shellchemy help"`."
  fi
}

__shellchemy_cd() {
  print_info "Changing directory to `color_cyan shellchemy`...";
  run_cmd "cd $shellchemy_path";
}
__shellchemy_restart() { 
  print_info "Restarting shellchemy...";
  run_cmd ". $shellchemy_path/index";
}